name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Build site
      run: bundle exec jekyll build

    - name: Deploy site
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      if: github.ref == 'refs/heads/main'
      with:
        server: web4.ipp-webspace.net
        username: qties-web
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./_site/
        security: strict
