name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Cache Ruby dependencies
      uses: actions/cache@v2.1.2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install Ruby dependencies
      run: bundle install
    - name: Build site
      run: bundle exec jekyll build

    - name: Deploy site
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      if: github.ref == 'refs/heads/main'
      with:
        server: web4.ipp-webspace.net
        username: qties-web
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./_site/
        security: strict
